2022-07-15 15:33:38,151 INFO    MainThread:1057964 [wandb_setup.py:_flush():76] Configure stats pid to 1057964
2022-07-15 15:33:38,151 INFO    MainThread:1057964 [wandb_setup.py:_flush():76] Loading settings from /home3/ebrahim/.config/wandb/settings
2022-07-15 15:33:38,151 INFO    MainThread:1057964 [wandb_setup.py:_flush():76] Loading settings from /home3/ebrahim/isr/wandb/settings
2022-07-15 15:33:38,151 INFO    MainThread:1057964 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2022-07-15 15:33:38,151 INFO    MainThread:1057964 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'run.py', 'program': 'run.py'}
2022-07-15 15:33:38,151 INFO    MainThread:1057964 [wandb_init.py:_log_setup():461] Logging user logs to /home3/ebrahim/isr/wandb/run-20220715_153338-3ht6264o/logs/debug.log
2022-07-15 15:33:38,151 INFO    MainThread:1057964 [wandb_init.py:_log_setup():462] Logging internal logs to /home3/ebrahim/isr/wandb/run-20220715_153338-3ht6264o/logs/debug-internal.log
2022-07-15 15:33:38,151 INFO    MainThread:1057964 [wandb_init.py:init():495] calling init triggers
2022-07-15 15:33:38,151 INFO    MainThread:1057964 [wandb_init.py:init():498] wandb.init called with sweep_config: {}
config: {'max_length': 9, 'test_list_length': 6, 'num_cycles': 200000, 'train_batch': 1, 'test_size': 5000, 'num_letters': 26, 'hs': 200, 'lr': 0.001, 'stopping_criteria': 0.58, 'feedback_scaling': 1.0, 'opt': 'SGD', 'momentum': 0.9, 'nonlin': 'sigmoid', 'clipping': False, 'clip_factor': 10}
2022-07-15 15:33:38,151 INFO    MainThread:1057964 [wandb_init.py:init():548] starting backend
2022-07-15 15:33:38,151 INFO    MainThread:1057964 [backend.py:_multiprocessing_setup():97] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2022-07-15 15:33:38,160 INFO    MainThread:1057964 [backend.py:ensure_launched():217] starting backend process...
2022-07-15 15:33:38,166 INFO    MainThread:1057964 [backend.py:ensure_launched():222] started backend process with pid: 1058127
2022-07-15 15:33:38,167 INFO    MainThread:1057964 [wandb_init.py:init():558] backend started and connected
2022-07-15 15:33:38,170 INFO    MainThread:1057964 [wandb_init.py:init():634] updated telemetry
2022-07-15 15:33:38,187 INFO    MainThread:1057964 [wandb_init.py:init():665] communicating run to backend with 30 second timeout
2022-07-15 15:34:04,598 ERROR   Thread-1  :1057964 [internal_api.py:execute():161] 500 response executing GraphQL.
2022-07-15 15:34:04,598 ERROR   Thread-1  :1057964 [internal_api.py:execute():162] {"error":"internal database error"}
2022-07-15 15:34:04,598 ERROR   Thread-1  :1057964 [retry.py:__call__():132] Retry attempt failed:
Traceback (most recent call last):
  File "/home3/ebrahim/.local/lib/python3.8/site-packages/wandb/sdk/lib/retry.py", line 108, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home3/ebrahim/.local/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 158, in execute
    return self.client.execute(*args, **kwargs)
  File "/home3/ebrahim/.local/lib/python3.8/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/home3/ebrahim/.local/lib/python3.8/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/home3/ebrahim/.local/lib/python3.8/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/transport/requests.py", line 39, in execute
    request.raise_for_status()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://api.wandb.ai/graphql
2022-07-15 15:34:08,189 INFO    MainThread:1057964 [interface_shared.py:_communicate_run():326] couldn't get run from backend
2022-07-15 15:34:08,189 ERROR   MainThread:1057964 [wandb_init.py:init():674] backend process timed out
2022-07-15 15:34:08,189 ERROR   MainThread:1057964 [wandb_init.py:init():685] encountered error: Error communicating with wandb process
try: wandb.init(settings=wandb.Settings(start_method='fork'))
or:  wandb.init(settings=wandb.Settings(start_method='thread'))
For more info see: https://docs.wandb.ai/library/init#init-start-error
2022-07-15 15:34:27,697 ERROR   Thread-1  :1057964 [internal_api.py:execute():161] 500 response executing GraphQL.
2022-07-15 15:34:27,697 ERROR   Thread-1  :1057964 [internal_api.py:execute():162] {"error":"internal database error"}
2022-07-15 15:34:29,156 WARNING MainThread:1057964 [wandb_init.py:init():1064] interrupted
Traceback (most recent call last):
  File "/home3/ebrahim/.local/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 1043, in init
    run = wi.init()
  File "/home3/ebrahim/.local/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 689, in init
    backend.cleanup()
  File "/home3/ebrahim/.local/lib/python3.8/site-packages/wandb/sdk/backend/backend.py", line 248, in cleanup
    self.wandb_process.join()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 149, in join
    res = self._popen.wait(timeout)
  File "/usr/lib/python3.8/multiprocessing/popen_fork.py", line 47, in wait
    return self.poll(os.WNOHANG if timeout == 0.0 else 0)
  File "/usr/lib/python3.8/multiprocessing/popen_fork.py", line 27, in poll
    pid, sts = os.waitpid(self.pid, flag)
KeyboardInterrupt
