2022-07-15 15:33:39,032 INFO    MainThread:1058127 [internal.py:wandb_internal():90] W&B internal server running at pid: 1058127, started at: 2022-07-15 15:33:39.032403
2022-07-15 15:33:39,033 INFO    WriterThread:1058127 [datastore.py:open_for_write():75] open: /home3/ebrahim/isr/wandb/run-20220715_153338-3ht6264o/run-3ht6264o.wandb
2022-07-15 15:33:39,035 DEBUG   SenderThread:1058127 [sender.py:send():236] send: header
2022-07-15 15:33:39,035 DEBUG   SenderThread:1058127 [sender.py:send():236] send: run
2022-07-15 15:34:03,242 ERROR   SenderThread:1058127 [internal_api.py:execute():161] 500 response executing GraphQL.
2022-07-15 15:34:03,243 ERROR   SenderThread:1058127 [internal_api.py:execute():162] {"error":"internal database error"}
2022-07-15 15:34:03,243 ERROR   SenderThread:1058127 [retry.py:__call__():132] Retry attempt failed:
Traceback (most recent call last):
  File "/home3/ebrahim/.local/lib/python3.8/site-packages/wandb/sdk/lib/retry.py", line 108, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home3/ebrahim/.local/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 158, in execute
    return self.client.execute(*args, **kwargs)
  File "/home3/ebrahim/.local/lib/python3.8/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/home3/ebrahim/.local/lib/python3.8/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/home3/ebrahim/.local/lib/python3.8/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/transport/requests.py", line 39, in execute
    request.raise_for_status()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://api.wandb.ai/graphql
2022-07-15 15:34:08,190 DEBUG   HandlerThread:1058127 [handler.py:handle_request():140] handle_request: shutdown
2022-07-15 15:34:08,190 INFO    HandlerThread:1058127 [handler.py:finish():806] shutting down handler
2022-07-15 15:34:08,224 ERROR   SenderThread:1058127 [internal_api.py:execute():161] 500 response executing GraphQL.
2022-07-15 15:34:08,225 ERROR   SenderThread:1058127 [internal_api.py:execute():162] {"error":"internal database error"}
2022-07-15 15:34:09,049 INFO    WriterThread:1058127 [datastore.py:close():279] close: /home3/ebrahim/isr/wandb/run-20220715_153338-3ht6264o/run-3ht6264o.wandb
2022-07-15 15:34:26,446 ERROR   SenderThread:1058127 [internal_api.py:execute():161] 500 response executing GraphQL.
2022-07-15 15:34:26,447 ERROR   SenderThread:1058127 [internal_api.py:execute():162] {"error":"internal database error"}
2022-07-15 15:34:31,034 INFO    MainThread:1058127 [internal.py:handle_exit():80] Internal process exited
